### ISSUE TITLE
Says username and email is in use when nothing is in database

### ISSUE THREAD

**Issue by ghost** [therecluse26/PHP-Login#65] opened 2017-02-09 17:19 UTC
I keep getting the issue in my register form saying that the username or email is already in use.  
What do I need to do to fix it.
The table I am entering values into is empty so this issue shouldn't be happening.

**Comment by pjk505** [comment] 2017-02-23 16:50
I just had the same problem. I have found that if an admin email address is set in the config file, then that email address is put into the database rather than the new user's address. The new user email needs to be assigned to $newemail at the beginning of createuser.php in all cases, and then the test for admin email placed after the email is entered into the database (i.e. to change at that point which address will be used for the verify email). Move the following code to directly before 'send verification email':

if (isset($admin_email)) {

				$newemail = $admin_email;

			}

**Comment by Mongoosex** [comment] 2017-05-10 11:57
Hello.

 I am having similar problem(s). After entering a new user, with new username and new email address i keep geting the same "response" that the username and or the email is in use - but it is not true, there are no such entries in the DB, also the sql entry is executed without any problems. After that, if i keep waiting patiently after submiting the data, after like 30 seconds, i get the success response and voila, it is all ok. Admin email is not set. In fact, it is no matter...regarding this problem. Basically>send form>validation>mysqli ok>error response username/email is in use>30+ seconds>success response...everything is ok...?!

**Comment by coggie** [comment] 2017-05-11 06:41
I had the same problem with this months ago but yet it's still the same
nobody managed to fix this error yet!

**Comment by Mongoosex** [comment] 2017-05-11 12:01
It will need some testing but i think the problem is that SOME people (like me for example) are moving the jquery and critical scripts from the php part to the html head part, or some of those scripts. I guess it is also important to keep the order of scripts as they stand in the signup.php file located here on github. After testing it few times, it seems like ok now, except the fact that for a succesfull registration i have to wait the loader gif to do his job :) ...while i was writing this text i found that the code on git hub is perfectly fine :)  /me hiding in flames atm :D ....

**Comment by kirkisanon** [comment] 2017-06-14 04:58
This have to seem to work for me to let new to be added in no problems for me.
    //Enables moderator verification (overrides user self-verification emails)
if (isset($admin_email)) {

    $newemail = $_POST['email'];
}

//Validation rules
if ($pw1 != $pw2) {

**Closed** 2018-06-16 02:57 UTC
