### ISSUE TITLE
Logged in as ordinary admin, not super

### ISSUE THREAD

**Issue by Looxoor** [therecluse26/PHP-Login#78] opened 2017-03-20 14:34 UTC
Hi!

First of all, thanks for a nice and simple system!

I recently moved all sites to a new server and after that everything still works as it should expect that I'm no longer a super admin.

I haven't noticed anything other than that and can't see anything I've done wrong.
Where and how is it tested?

The address is https://holwarehouse.ddns.net if you'd like to poke around.

**Comment by therecluse26** [comment] 2017-03-20 20:09
Yeah, I noticed that was an issue that began happening with the installer,
but I have no idea as of now what the cause is, so I'll be looking into
that this week and writing a bit more documentation so you guys can at
least get the thing up and running without a fully functional installer. A
web-based installer is turning out to be more tricky cross-platform than I
had anticipated, and I just started a new job, so I've been a bit swamped.
Sorry about the further delays on this.

**Comment by Looxoor** [comment] 2017-03-20 20:12
That's great to hear, no stress!
Though I think that answer was meant for issue #77 instead. :)

**Comment by therecluse26** [comment] 2017-03-20 20:14
I meant the superadmin trigger wasn't firing properly during installation.

Also, I use ddns.net for my home sandbox as well :) It's great

**Comment by Looxoor** [comment] 2017-03-20 20:16
Aah, I see!
The thing is it worked flawlessly until I moved it from my NAS as host to a new home server.

I guess I'll just have to reinstall?

**Comment by therecluse26** [comment] 2017-03-20 20:19
You could go into your admins table in mysql and update "superadmin" on
your id to 1, which should give you access to the superadmin functions
after you log out and back in. You can edit all of the site config values
as a superadmin, which is needed to  change your smtp settings, though you
could also do that through the database appConfig table if you needed to.

**Comment by therecluse26** [comment] 2017-03-20 20:21
Now, I can't guarantee that anything else isn't broken, but as for now I
think that's the only system breaking issue with the installer for now.
There also might be file permission problems too, you'll need look those
over, and ensure that your user/avatars folder has write access. I think
that's the only one that needs write access from what I can remember.

**Comment by Looxoor** [comment] 2017-03-20 21:08
The thing is that the database is correct too, my user has superadmin and everything, the only thing that's changed is the physical location of the files.

I thought maybe it was a problem with the checks, client side, but both cookies are present so I wonder if it's only the 1 on superadmin in the db that is checked or are there any other things that can malfunction?

**Comment by therecluse26** [comment] 2017-03-22 12:53
I don't see how that would be if the superadmin is checked in the admins
table, since the page header runs all of those checks... did you check to
make sure that the user id is lining up between the members and admins
table? What's the login info so I can poke around in your system?

**Comment by Looxoor** [comment] 2017-03-22 13:08
Yeah I opened the database with phpmyadmin and the user id's and admin id's are linked and identical.

Sure, 
U: Looxoor 
P: Logintest1 (changed for this purpose)

**Closed** 2018-06-16 02:48 UTC
